spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost:3306/wx?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 333
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
server:
  port: 8080

zzy:
  remotePath: localhost
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_del # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
